[tool.poetry]
name = "ba-crew-concept1"
version = "0.1.0"
description = ""
authors = ["h.singh@infogain.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
